name: Deploy to AKS

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Azure login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Get AKS credentials
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group "rg-skhan-demo-aks" --name "skhanaks" --admin

      # 4. Install NGINX Ingress Controller
      - name: Install NGINX Ingress Controller
        run: |
          kubectl create namespace ingress-nginx --dry-run=client -o yaml | kubectl apply -f -
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --set controller.replicaCount=2 \
            --set controller.nodeSelector."kubernetes\.io/os"=linux \
            --set defaultBackend.nodeSelector."kubernetes\.io/os"=linux

      # 5. Install cert-manager
      - name: Install cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.yaml
          echo "Waiting for cert-manager pods to be ready..."
          kubectl rollout status deployment cert-manager -n cert-manager --timeout=120s
          kubectl rollout status deployment cert-manager-cainjector -n cert-manager --timeout=120s
          kubectl rollout status deployment cert-manager-webhook -n cert-manager --timeout=120s

      # 6. Apply ClusterIssuer
      - name: Apply ClusterIssuer
        run: kubectl apply -f k8s/cluster-issuer.yaml

      # 7. Deploy Application (Deployment + Service)
      - name: Deploy App
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # 8. Apply Ingress with TLS
      - name: Apply Ingress
        run: kubectl apply -f k8s/ingress.yaml
