name: Deploy to AKS

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Azure login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Get AKS credentials
      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group "rg-skhan-demo-aks" \
            --name "skhanaks" \
            --admin

      # 4. Install NGINX Ingress Controller
      - name: Install NGINX Ingress Controller
        run: |
          kubectl create namespace ingress-nginx --dry-run=client -o yaml | kubectl apply -f -
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --set controller.replicaCount=2 \
            --set controller.nodeSelector."kubernetes\.io/os"=linux \
            --set defaultBackend.nodeSelector."kubernetes\.io/os"=linux

      # 5. Create TLS Secret from certs directory
      - name: Create TLS Secret
        run: |
          kubectl create secret tls skhan-tech-tls \
            --cert=certs/skhan.tech.crt \
            --key=certs/skhan.tech.key \
            --namespace default \
            --dry-run=client -o yaml | kubectl apply -f -

      # 6. Deploy Application (Deployment + Service)
      - name: Deploy App
        run: |
          kubectl apply -f manifest/deploy-app.yaml
          kubectl apply -f manifest/svc-app.yaml

      # 7. Apply Ingress with TLS
      - name: Apply Ingress
        run: kubectl apply -f manifest/ingress.yaml
